<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="arm" params="name mirror mirror_dae  *origin">  
        
        <joint name="${name}_shoulder_yaw_joint" type="revolute">
       
            <xacro:if value="${(mirror_dae == True)}">
            <origin rpy="0 0 0" xyz="0.0 0.047 0.1725"/>
            </xacro:if>
            
            <xacro:if value="${(mirror_dae == False)}">
            <origin rpy="0 0 0" xyz="0.0 -0.047 0.1725"/>
            </xacro:if>          
          
            <parent link="trunk"/>
            <child link="${name}_shoulder_yaw_link"/>
            <axis xyz="0 0 1"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${shoulder_yaw_torque_max}" velocity="${shoulder_yaw_velocity_max}" lower="${shoulder_yaw_min}" upper="${shoulder_yaw_max}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${shoulder_yaw_torque_max}" velocity="${shoulder_yaw_velocity_max}" lower="${-shoulder_yaw_max}" upper="${-shoulder_yaw_min}"/>
            </xacro:if>  
        </joint>
        <link name="${name}_shoulder_yaw_link">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 ${shoulder_yaw_offset_z}"/>

            <xacro:if value="${(mirror_dae == True)}">
            <geometry>
                <mesh filename="file://$(find hector_assets)/models/meshes/hector_arm/ShoulderYaw_L.stl" scale="1 1 1"/>
            </geometry>
            </xacro:if>

            <xacro:if value="${(mirror_dae == False)}">
            <geometry>
                <mesh filename="file://$(find hector_assets)/models/meshes/hector_arm/ShoulderYaw_R.stl" scale="1 1 1"/>
            </geometry>
            </xacro:if>

            <material name="grey"/>
            </visual>

            <collision>
                <origin rpy="${PI/2.0} 0 0" xyz="0 ${-(shoulder_yaw_length/2.0-shoulder_yaw_offset)*mirror} 0"/>
                <geometry>
                    <cylinder length="${shoulder_yaw_length}" radius="${shoulder_yaw_radius}"/>
                </geometry>
            </collision>

            <inertial>
                <origin rpy="0 0 0" xyz="${shoulder_yaw_com_x} ${shoulder_yaw_com_y*mirror} ${shoulder_yaw_com_z}"/>
                <mass value="${shoulder_yaw_mass}"/>
                <inertia
                    ixx="${shoulder_yaw_ixx}" ixy="${shoulder_yaw_ixy*mirror}" ixz="${shoulder_yaw_ixz}"
                    iyy="${shoulder_yaw_iyy}" iyz="${shoulder_yaw_iyz*mirror}"
                    izz="${shoulder_yaw_izz}"/>       
            </inertial>          
        </link>

        <joint name="${name}_shoulder_pitch_joint" type="revolute">
            <xacro:if value="${(mirror_dae == True)}">
            <origin rpy="0 0 0" xyz="0.0 0.045 -0.018"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
            <origin rpy="0 0 0" xyz="0.0 -0.045 -0.018"/>
            </xacro:if>                
            <parent link="${name}_shoulder_yaw_link"/>
            <child link="${name}_shoulder_pitch_link"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${shoulder_pitch_torque_max}" velocity="${shoulder_pitch_velocity_max}" lower="${shoulder_pitch_min}" upper="${shoulder_pitch_max}"/>

        </joint>
        <link name="${name}_shoulder_pitch_link">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            
            <xacro:if value="${(mirror_dae == True)}">
            <geometry>
                <mesh filename="file://$(find hector_assets)/models/meshes/hector_arm/ShoulderPitch_L.stl" scale="1 1 1"/>
            </geometry>
            </xacro:if>
            
            <xacro:if value="${(mirror_dae == False)}">
            <geometry>
                <mesh filename="file://$(find hector_assets)/models/meshes/hector_arm/ShoulderPitch_R.stl" scale="1 1 1"/>
            </geometry>     
            </xacro:if> 
            
            <material name="gold"/>
            </visual>
           <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 ${-shoulder_pitch_length/2.0}"/>
                <geometry>
                    <box size="${shoulder_pitch_length} ${shoulder_pitch_width} ${shoulder_pitch_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${shoulder_pitch_com_x} ${shoulder_pitch_com_y*mirror} ${shoulder_pitch_com_z}"/>
                <mass value="${shoulder_pitch_mass}"/>
                <inertia
                    ixx="${shoulder_pitch_ixx}" ixy="${shoulder_pitch_ixy*mirror}" ixz="${shoulder_pitch_ixz}"
                    iyy="${shoulder_pitch_iyy}" iyz="${shoulder_pitch_iyz*mirror}"
                    izz="${shoulder_pitch_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_shoulder_roll_joint" type="revolute">
            <xacro:if value="${(mirror_dae == True)}">
            <origin rpy="0 0 0" xyz="-0.0135 0.045 0.0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
            <origin rpy="0 0 0" xyz="-0.0135 -0.045 0.0"/>
            </xacro:if>                
            <parent link="${name}_shoulder_pitch_link"/>
            <child link="${name}_shoulder_roll_link"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${shoulder_roll_torque_max}" velocity="${shoulder_roll_velocity_max}" lower="${shoulder_roll_min}" upper="${shoulder_roll_max}"/>
        </joint>
        
        <link name="${name}_shoulder_roll_link">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            
            <xacro:if value="${(mirror_dae == True)}">
            <geometry>
                <mesh filename="file://$(find hector_assets)/models/meshes/hector_arm/UpperArmRoll_L.stl" scale="1 1 1"/>
            </geometry>
            </xacro:if>
            
            <xacro:if value="${(mirror_dae == False)}">
            <geometry>
                <mesh filename="file://$(find hector_assets)/models/meshes/hector_arm/UpperArmRoll_R.stl" scale="1 1 1"/>
            </geometry>     
            </xacro:if> 
            
            <material name="grey"/>
            </visual>
           <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="${shoulder_roll_offset_x} 0 ${-shoulder_roll_length/2.0}"/>
                <geometry>
                    <box size="${shoulder_roll_length} ${shoulder_roll_width} ${shoulder_roll_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${shoulder_roll_com_x} ${shoulder_roll_com_y*mirror} ${shoulder_roll_com_z}"/>
                <mass value="${shoulder_roll_mass}"/>
                <inertia
                    ixx="${shoulder_roll_ixx}" ixy="${shoulder_roll_ixy*mirror}" ixz="${shoulder_roll_ixz}"
                    iyy="${shoulder_roll_iyy}" iyz="${shoulder_roll_iyz*mirror}"
                    izz="${shoulder_roll_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_elbow_joint" type="revolute">
            <origin rpy="0 0 0" xyz="${elbow_offset_x} 0.0 -0.20"/>
            <parent link="${name}_shoulder_roll_link"/>
            <child link="${name}_elbow_link"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${elbow_torque_max}" velocity="${elbow_velocity_max}" lower="${elbow_min}" upper="${elbow_max}"/>
        </joint>
        <link name="${name}_elbow_link">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find hector_assets)/models/meshes/hector_arm/ForeArmPitch.stl" scale="1 1 1"/>
            </geometry>
            <material name="grey"/>
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 ${-elbow_length/2.0}"/>
                <geometry>
                    <box size="${elbow_length} ${elbow_width} ${elbow_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${elbow_com_x} ${elbow_com_y} ${elbow_com_z}"/>
                <mass value="${elbow_mass}"/>
                <inertia
                    ixx="${elbow_ixx}" ixy="${elbow_ixy}" ixz="${elbow_ixz}"
                    iyy="${elbow_iyy}" iyz="${elbow_iyz}"
                    izz="${elbow_izz}"/>       
            </inertial>
        </link>
        <joint name="${name}_arm_EE_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0.0 0.0 -0.20"/>
            <parent link="${name}_elbow_link"/>
            <child link="${name}_arm_EE_link"/>
        </joint>
        <link name="${name}_arm_EE_link">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="0.01"/>
            </geometry>
            <material name="grey"/>
            </visual>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="0.0001"/>
                <inertia
                    ixx="0.0000001" ixy="0.0000001" ixz="0.0000001"
                    iyy="0.0000001" iyz="0.0000001"
                    izz="0.0000001"/>       
            </inertial>
        </link>        
    </xacro:macro>
</robot>
